import data from './catalog.json';

export interface Tactic {
  shortname: string;
  id: string;
  name: string;
}

export interface Technique {
  id: string;
  name: string;
  tactics: string[];
}

export interface Catalog {
  version: string;
  copyright: string;
  tactics: Tactic[];
  /** Active techniques and sub-techniques, by ID. */
  techniques: Technique[];
  /** A revoked ID and the active one that replaced it. */
  revoked: Record<string, string>;
  /** Retired without a replacement. */
  deprecated: string[];
}

/** Enterprise ATT&CK, generated by scripts/attack-catalog.mjs; never edited by hand. */
export const CATALOG = data as Catalog;

const ACTIVE = new Map(CATALOG.techniques.map((t) => [t.id, t]));
const TACTIC_NAMES = new Map(CATALOG.tactics.map((t) => [t.shortname, t.name]));

/** A tactic as ATT&CK names it, in every view; a short name the catalogue lacks is spelled out word by word. */
export function tacticName(shortname: string): string {
  return TACTIC_NAMES.get(shortname) ?? shortname.split('-').map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}

export function technique(id: string): Technique | undefined {
  return ACTIVE.get(id);
}

export function isActive(id: string): boolean {
  return ACTIVE.has(id);
}

export function parentId(id: string): string {
  return id.split('.')[0];
}

export function subTechniques(parent: string): Technique[] {
  return CATALOG.techniques.filter((t) => t.id.startsWith(`${parent}.`));
}

export function replacement(id: string): Technique | undefined {
  const to = CATALOG.revoked[id];
  return to === undefined ? undefined : ACTIVE.get(to);
}
